package com.prasadnp.caching.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * Entity class representing a Product in the system.
 * Maps to a database table via JPA annotations.
 * 
 * @author devprasadnp
 */
@Entity  // Marks this class as a JPA entity to be managed by the persistence context.
public class Product {

    @Id  // Marks the field below as the primary key of this entity.
    @GeneratedValue(strategy = GenerationType.IDENTITY)  // Specifies that the primary key value will be generated by the database (auto-increment).
    private int id;

    private String name;         // Name of the product.
    private String description;  // Description of the product.

    /**
     * Default no-argument constructor required by JPA.
     */
    public Product() {
    }

    /**
     * Constructor to create a Product with all fields.
     * @param id the unique identifier of the product.
     * @param name the product's name.
     * @param description a short description of the product.
     */
    public Product(int id, String name, String description) {
        super();
        this.id = id;
        this.name = name;
        this.description = description;
    }

    /**
     * Gets the product ID.
     * @return the ID of the product.
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the product ID.
     * @param id the ID to set.
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Gets the product name.
     * @return the name of the product.
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the product name.
     * @param name the name to set.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Gets the product description.
     * @return the description of the product.
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the product description.
     * @param description the description to set.
     */
    public void setDescription(String description) {
        this.description = description;
    }
}
